### ISSUE TITLE
Microsoft.Azure.EventHubs Package is deprecated

### ISSUE THREAD

**Issue by UKHOGreg** [UKHO/EventHub-Logging-Provider#17]
`Microsoft.Azure.EventHubs` Package is deprecated and should be replaced by `Azure.Messaging.EventHubs`

> Please note, a newer package Azure.Messaging.EventHubs is available as of February 2020. While this package will continue to receive critical bug fixes, we strongly encourage you to upgrade. Read the migration guide at https://aka.ms/azsdk/net/migrate/eh for more details.

**Comment by hwoodiwiss** [comment]
Just as a note to this, the current deprecated EventHubs package uses an outdated version of Microsoft.Azure.Amqp, which is incompatible with .NET 6.

The workaround is to manually include a later Microsoft.Azure.Amqp, however it would be good to see this fixed in this package, and I'm happy to make myself available  to get this done quickly.

**Comment by rockydevnet** [comment]
Resolved by #53
